
import static java.lang.System.exit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import javax.swing.JButton;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ferha
 */
public class petlogin extends javax.swing.JFrame  {
   
    
    
    LocalDateTime ld=LocalDateTime.now();
          
       
DateTimeFormatter df = DateTimeFormatter.ofPattern("dd  MMMM  yyyy "
        + " h:mm");
String date=df.format(ld);
   

    /**
     * Creates new form petlogin
     */
    public petlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Edetitor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edev = new javax.swing.JButton();
        kytlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cıkıs = new javax.swing.JButton();
        giris = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edev.setIcon(new javax.swing.ImageIcon("/Users/ferhattoson/Downloads/e-devlet-LIBg-2.jpg")); // NOI18N
        edev.setText("jButton3");
        getContentPane().add(edev, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 160, 90));

        kytlbl.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        kytlbl.setForeground(new java.awt.Color(0, 51, 102));
        kytlbl.setText("kayıt ol...");
        kytlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kytlblMouseClicked(evt);
            }
        });
        getContentPane().add(kytlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 179, 67));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("TC KİMLİK:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, 40));

        jPasswordField1.setText("<sxlkxljolj");
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 150, 40));

        jTextField1.setText("56252255232");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 150, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("ŞİFRE:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 80, 30));

        cıkıs.setBackground(new java.awt.Color(255, 204, 204));
        cıkıs.setText("ÇIKIŞ");
        cıkıs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cıkısActionPerformed(evt);
            }
        });
        getContentPane().add(cıkıs, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 130, 60));

        giris.setBackground(new java.awt.Color(204, 255, 204));
        giris.setText("GİRİŞ");
        giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisActionPerformed(evt);
            }
        });
        getContentPane().add(giris, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 100, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon("/Users/ferhattoson/Desktop/MER.gif")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 0, 110, 130));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resized_images.jpeg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-14, -14, 520, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisActionPerformed

        
        pet p=new pet();



p.setVisible(true);// TODO add your handling code here:

dispose();
    }//GEN-LAST:event_girisActionPerformed

    private void cıkısActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cıkısActionPerformed
        // TODO add your handling code here:
        JFrame f=new JFrame("çıkış");
if(JOptionPane.showConfirmDialog(f,"çıkmak istediğinize emin misiniz?","çıkış",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
{// TODO add your handling code here:
System.exit(0);
    }       
    }//GEN-LAST:event_cıkısActionPerformed

    private void kytlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kytlblMouseClicked
kayıtol ko=new kayıtol();
ko.setVisible(true);



        // TODO add your handling code here:
    }//GEN-LAST:event_kytlblMouseClicked
 
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(petlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(petlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(petlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(petlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new petlogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cıkıs;
    private javax.swing.JButton edev;
    private javax.swing.JButton giris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel kytlbl;
    // End of variables declaration//GEN-END:variables

}
   
   

/*JFrame f=new JFrame("çıkış");
if(JOptionPane.showConfirmDialog(f,"çıkmak istediğinize emin misiniz?","çıkış",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
{// TODO add your handling code here:
System.exit(0);
    }          */